### ISSUE TITLE
Entry point from unity editor

### ISSUE THREAD

**Issue by KisaragiEffective** [123tris/CTB-Editor#2]

**Comment by 123tris** [comment]
Do you have any particular question in regards to running the project in Unity?

**Comment by KisaragiEffective** [comment]
unity usage is written on my book, so its ok :thinking: 
i looked into like every directory, but can't found `main` or something like entry point... did i something miss?

**Comment by 123tris** [comment]
It's a Unity project, which means only scripts are contained in the C# solution which are called by Unity through their mono compiler.

TL;DR There is no main or entry point. Most scripts are components to gameobjects
